name: flutter_analytics
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_analytics: ^10.7.2

  firebase_crashlytics: ^3.4.8

  firebase_core: ^2.24.0

  cupertino_icons: ^1.0.2

  get_it: ^7.6.4

  go_router: ^12.1.1

dev_dependencies:
  build_runner: any

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  go_router_builder: any

  build_verify: any

flutter:
  uses-material-design: true
